### ISSUE TITLE
Issues using intact query command with additional parameters

### ISSUE THREAD

**Issue by risserlin** [EBI-IntAct/IntActApp#5]
When I run the following command from R I can get results:
intact query seedTerms='P49418 Q8N729 Q5VZR2 Q8WYP3 Q3SY00 Q9NPI5 Q7RTP6 A2A288 A1X283 P52849 Q717R9 Q96MF6 Q8N158 Q08345 Q5JSZ5 Q6ZSJ9 A8MTA8 Q86VR8 Q9BWX5 P10826 Q8IY33 Q9UQ88 O14545 Q9Y3S1 O43295 Q6NSI4 Q6J9G0 Q8TB24 Q96J02 Q9H1Q7 Q99973 P08151 O60890 Q8NBV8 Q8TD84 Q6GQQ9 O15240 Q9HBG7 Q8WZ71 Q2KJY2 Q14160 Q9UHG0 H7BZ55 Q02246 Q6ZRS2 Q9Y4E6 O95180 Q13177 Q6ZNL6 Q9UMN6 Q9UK61 Q14118 P50570 Q9Y6N7 O60486 P98160 Q96RT6 Q14183 Q8IXW0 Q93074 Q8N4Y2 Q5U5Q3 Q9HCK4 Q8WWW0 Q9HCK1 Q5T9C2 P46013 Q6ZU52 Q9H427 O43426 O43184 P57058 P54259 Q8WWN8 Q9HCI5 Q08493 Q96T23 Q14624 Q99743 Q96AY4 Q96F05 O15211 Q6UXB0 Q7Z6E9 Q9UJY5 Q8NDB2 O94875 Q8WXE0 Q6F5E8 Q8WUF5 Q8NI99 Q6ZS10 Q12756 Q5SYB0 Q9UPS6 Q96DX4 Q7Z7G1'

But if I modify my command by adding parameters for example:
intact query includeSeedPartners=false exactQuery=true taxons=9606 seedTerms='P49418 Q8N729 Q5VZR2 Q8WYP3 Q3SY00 Q9NPI5 Q7RTP6 A2A288 A1X283 P52849 Q717R9 Q96MF6 Q8N158 Q08345 Q5JSZ5 Q6ZSJ9 A8MTA8 Q86VR8 Q9BWX5 P10826 Q8IY33 Q9UQ88 O14545 Q9Y3S1 O43295 Q6NSI4 Q6J9G0 Q8TB24 Q96J02 Q9H1Q7 Q99973 P08151 O60890 Q8NBV8 Q8TD84 Q6GQQ9 O15240 Q9HBG7 Q8WZ71 Q2KJY2 Q14160 Q9UHG0 H7BZ55 Q02246 Q6ZRS2 Q9Y4E6 O95180 Q13177 Q6ZNL6 Q9UMN6 Q9UK61 Q14118 P50570 Q9Y6N7 O60486 P98160 Q96RT6 Q14183 Q8IXW0 Q93074 Q8N4Y2 Q5U5Q3 Q9HCK4 Q8WWW0 Q9HCK1 Q5T9C2 P46013 Q6ZU52 Q9H427 O43426 O43184 P57058 P54259 Q8WWN8 Q9HCI5 Q08493 Q96T23 Q14624 Q99743 Q96AY4 Q96F05 O15211 Q6UXB0 Q7Z6E9 Q9UJY5 Q8NDB2 O94875 Q8WXE0 Q6F5E8 Q8WUF5 Q8NI99 Q6ZS10 Q12756 Q5SYB0 Q9UPS6 Q96DX4 Q7Z7G1'

Cytoscape just hangs. 
Tried running from R and from cytoscape command panel.  It doesn't matter which of the parameters I use.  If I add anything beyond seedTerms Cytoscape hangs.

**Comment by EliotRagueneau** [comment]
I believe I've been able to reproduce the bug you had, and it was due to one of web service not responding.
This web service has now been restarted and it solved the problem on my side.
Could you please tell me if the problem is still occurring on your side? If yes, it means that there is a deeper problem and we'll need to investigate more on that.

Anyways, thank you very much for the feedback you provided us,
Eliot Ragueneau

**Comment by risserlin** [comment]
Thank you!  It is working now.
